### ISSUE TITLE
Compatibility with macOS Catalina

### ISSUE THREAD

**Issue by mariobrostech** [minecraft-linux/osx-packaging-scripts#3]
Hi!

Does anyone have any information on whether the Minecraft Bedrock Launcher is compatible with macOS Catalina? I'd assume the answer is no because the app appears as "Legacy Software" on macOS Mojave.

Just wanted to make sure this software would be compatible so I don't run into issues after the OS update.

Thank you!

**Comment by MCMrARM** [comment]
Wrong repo, and no, Catalina is not supported.
